### ISSUE TITLE
Should actions be in their own folder?

### ISSUE THREAD

**Issue by bvennam** [ibm-functions/package-cloud-object-storage#23]
Currently, we have actions living alongside the manifest file describing what's inside the package.  I think it is cleaner to put all the actions in an actions folder, especially if there are quite a few.  We do this for other templates, even though most of those templates have very few actions.
https://github.com/ibm-functions/template-cloud-object-storage/tree/master/runtimes/nodejs
https://github.com/ibm-functions/template-get-external-resource/tree/master/runtimes/nodejs
```
runtimes
    nodejs
        manifest.yaml
        actions
            action1
            action2
```

**Comment by eweiter** [comment]
I think it would be cleaner to have them in their own folder. 
@csantanapr You want to weigh in?  I'll make the change soon if I don't hear from you.

**Comment by csantanapr** [comment]
Ah cool good improvement 
Didn’t notice. 
Good to have manifest by itself and all actions in the actions directory.

**Comment by csantanapr** [comment]
Belinda I thought it followed the other templates format already

**Comment by csantanapr** [comment]
Good catch

**Comment by bvennam** [comment]
merged June 11th.
